# Новости курса {-}

------

## 2023-10-24 {-}
* Опубликован двенадцатый урок - [Разработка пакета обёртки над API (пакет httr2)].

## 2023-10-17 {-}
* Опубликован одиннадцатый урок - [Публикация в CRAN].

## 2023-10-10 {-}
* Опубликован десятый урок курса - [Разработка сайта пакета (пакет pkgdown)].

## 2023-10-07 {-}
* В курс добавлено видео [Вводное слово].

## 2023-10-03 {-}
* Опубликован девятый урок курса [Виньетки и прочая опциональная документация пакета]

## 2023-09-25 {-}
* Опубликован весьмой урок курса [Написание документации к функциям пакета]

## 2023-09-19 {-}
* Опубликован седьмой урок курса [Разработка юнит-тестов к функциям пакета (пакет testthat)]
* Добавлена страница [Решение заданий]

## 2023-09-12 {-}
* Опубликован шестой урок [NAMESPACE - Зависимости пакета].

## 2023-09-05 {-}
* Опубликован пятный урок [DESCRIPTION - Метаданные пакета].

## 2023-08-31 {-}
* В описание каждого урока добавлена информация о том, какой матриал лежит в его основе. Большая часть уроков курса основаны на книге ["R Packages (2e)"](https://r-pkgs.org/), под авторством Хедли Викхема и Дженни Брайан.

## 2023-08-29 {-}
* Опубликован четвёртый урок курса [Добавление данных в пакет]

## 2023-08-28 {-}
* В программу курса добавлен урок Разработка пакета обёртки для Google API (пакет gargle)""

## 2023-08-22 {-}
* Опубликован третий урок курса [Рекомендации по организации R кода]

## 2023-08-16 {-}
* Доработана программа, урок по компонентам пакета был разбит на 2, организация кода в пакете и добавление данных в пакет

## 2023-08-15 {-}
* Сформирована первая версия программы курса
* Опубликован второй урок курса: [Настройка системы и интеграция с GitHub]
* На страницы курса добавлены кнопки поделиться в социальных сетях и подписаться на telegram и youtube каналы

## 2023-08-07 {-}
* Создан проект курса
* Видео первого урока опубликовано на YouTube
* Страница первого урока добавлена в курс: [Обзор рабочего процесса разработки пакета]
* Курс опубликован на [selesnow.github.io](https://selesnow.github.io/r_package_course/)

```{r, message=FALSE, echo=FALSE, warning=FALSE}
library(r2social)
r2social::r2social.scripts()
r2social::shareButton(link = "https://selesnow.github.io/r_package_course/", position = "inline", whatsapp = T, telegram = T, instagram = T)
r2social::connectButton(link = 'https://t.me/R4marketing', link.out = F, telegram = T, position = 'left')
r2social::connectButton(link = 'https://www.youtube.com/R4marketing/?sub_confirmation=1', link.out = F, youtube = T, position = 'right')
```